"""
Local config properties.
"""

DEBUG = True
ENV = 'local'
GOOGLE_API_KEY = None
GOOGLE_CSE_ID = None
MONGODB_DB = 'imagesearch'
MONGODB_HOST = '127.0.0.1'
MONGODB_PASSWORD = None
MONGODB_PORT = 27017
MONGODB_USERNAME = None
SECRET_KEY = 'default secret key'
SERVER_NAME = '127.0.0.1:5000'
SESSION_COOKIE_DOMAIN = '127.0.0.1:5000'
