---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: leader-election
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: leader-election
rules:
  - apiGroups:
      - ''
    resources:
      - endpoints
    verbs:
      - create
      - get
      - list
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: leader-election
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: leader-election
subjects:
  - kind: ServiceAccount
    name: leader-election
---
apiVersion: v1
kind: Service
metadata:
  name: leader-election-hazelcast-discovery
spec:
  selector:
    app: leader-election
  ports:
    - port: 5701
---
apiVersion: v1
kind: Service
metadata:
  name: leader-election
spec:
  ports:
    - port: 7080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: leader-election
  labels:
    app: leader-election
spec:
  replicas: 3
  selector:
    matchLabels:
      app: leader-election
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: leader-election
    spec:
      serviceAccountName: leader-election
      containers:
        - image: vanillaslice/leader-election
          name: leader-election
          ports:
            - containerPort: 7080
            - containerPort: 7081
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 7081
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 7081
            initialDelaySeconds: 300
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
---
