version: '3'
services:
  mongodb:
    image: mongo:4.1.9-xenial
    volumes:
      - ./mongodb/docker-entrypoint-initdb.d/local-user.js:/docker-entrypoint-initdb.d/local-user.js
      - ./mongodb/data/db:/data/db
  dawdle:
    build:
      context: .
      dockerfile: ./docker/local.Dockerfile
    ports:
      - 5000:8000
    environment:
      - DEBUG=True
      - ENV=local
      - MONGODB_DB=dawdle
      - MONGODB_HOST=mongodb
      - MONGODB_PASSWORD=local-user-password
      - MONGODB_PORT=27017
      - MONGODB_USERNAME=local-user
      - SECRET_KEY=super-secret-key
      - SERVER_NAME=127.0.0.1:5000
      - SESSION_COOKIE_DOMAIN=127.0.0.1:5000
      - WTF_CSRF_ENABLED=True
    volumes:
      - ./dawdle:/opt/app/dawdle
      - ./config.py:/opt/app/config.py
      - ./run.py:/opt/app/run.py
      - ./instance:/opt/app/instance
