sudo: true
dist: trusty
branches:
  only:
    - master
install:
  - sudo apt-get --yes install snapd
  - sudo snap install hugo
script:
  - /snap/bin/hugo
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: public
  on:
    branch: master
  fqdn: blog.mikelowe.xyz
