baseURL = "https://mikelowe.xyz"
languageCode = "en-us"
title = "Mike Lowe"
theme = "papermod"

[params]
env = "production"
title = "Mike Lowe"
description = "Senior Software Engineer at KrakenFlex"
author = "Mike Lowe"
keywords = ["software", "developer", "engineer", "krakenflex"]
defaultTheme = "auto"

[params.analytics.google]
SiteVerificationTag = "O8nQ3mb-lymo3nQFax5JRFE-mgmtxnLJ1H-ZIEdzSxQ"

[params.profileMode]
enabled = "true"
title = "Mike Lowe"
subtitle = "Senior Software Engineer at KrakenFlex"

[[params.socialIcons]]
name = "github"
url = "https://github.com/vanillaSlice"

[[params.socialIcons]]
name = "linkedin"
url = "https://uk.linkedin.com/"
