baseURL = "https://mikelowe.xyz"
languageCode = "en-us"
title = "Mike Lowe"
theme = "papermod"
enableRobotsTXT = "true"

[params]
env = "production"
title = "Mike Lowe"
description = "Lead Software Engineer at KrakenFlex"
author = "Mike Lowe"
keywords = ["mike lowe", "software", "developer", "engineer", "krakenflex", "manchester", "england", "uk"]
defaultTheme = "light"
disableThemeToggle = "true"
ShowBreadCrumbs = "true"

[params.analytics]
googlesiteVerificationTag = "O8nQ3mb-lymo3nQFax5JRFE-mgmtxnLJ1H-ZIEdzSxQ"

[params.profileMode]
enabled = "true"
title = "Mike Lowe"
subtitle = "Lead Software Engineer at KrakenFlex"

[[params.profileMode.buttons]]
name = "Projects"
url = "/projects"

[[params.profileMode.buttons]]
name = "Writings"
url = "/writings"

[[params.socialIcons]]
name = "github"
url = "https://github.com/vanillaSlice"

[[params.socialIcons]]
name = "linkedin"
url = "https://uk.linkedin.com/"
