name: Fractal Trees
on:
  pull_request:
    branches: main
    paths:
      - .github/workflows/fractal-trees.yml
      - projects/fractal-trees/**
  push:
    branches: main
    paths:
      - .github/workflows/fractal-trees.yml
      - projects/fractal-trees/**
jobs:
  Build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: projects/fractal-trees
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 10
      - run: npm ci
      - run: npm test
      - run: npm run build
      - uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: projects/fractal-trees/build
          production-branch: main
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: 98e98c58-1b6d-4b58-b6a9-aa3f70c4d979
