name: Game of Life
on:
  pull_request:
    branches: main
    paths:
      - .github/workflows/game-of-life.yml
      - projects/game-of-life/**
  push:
    branches: main
    paths:
      - .github/workflows/game-of-life.yml
      - projects/game-of-life/**
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: corretto
      - uses: gradle/gradle-build-action@v2
      - working-directory: projects/game-of-life
        run: |
          ./gradlew check
