name: Legacy One
on:
  pull_request:
    branches: main
    paths:
      - .github/workflows/legacy-one.yml
      - projects/legacy-one/**
  push:
    branches: main
    paths:
      - .github/workflows/legacy-one.yml
      - projects/legacy-one/**
jobs:
  Build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: projects/legacy-one
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 10
      - run: npm ci
      - run: npm test
      - run: npm run build
      - uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: projects/legacy-one/build
          production-branch: main
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: a00f0d16-d29c-4d2a-8311-2d60f15d7636
