name: Markdown Previewer
on:
  pull_request:
    branches: main
    paths:
      - .github/workflows/markdown-previewer.yml
      - projects/markdown-previewer/**
  push:
    branches: main
    paths:
      - .github/workflows/markdown-previewer.yml
      - projects/markdown-previewer/**
jobs:
  Build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: projects/markdown-previewer
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 10
      - run: npm ci
      - run: npm test
      - uses: codecov/codecov-action@v2
        with:
          flags: ReactGameOfLife
          fail_ci_if_error: true
      - run: npm run build
      - uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: projects/markdown-previewer/build
          production-branch: main
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ba5f39c9-d74b-49e3-803b-4807f68e7113
