name: Matrix Digital Rain
on:
  pull_request:
    branches: main
    paths:
      - .github/workflows/matrix-digital-rain.yml
      - projects/matrix-digital-rain/**
  push:
    branches: main
    paths:
      - .github/workflows/matrix-digital-rain.yml
      - projects/matrix-digital-rain/**
jobs:
  Build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: projects/matrix-digital-rain
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 10
      - run: npm ci
      - run: npm test
      - run: npm run build
      - uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: projects/matrix-digital-rain/build
          production-branch: main
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: 61d7a170-6ca0-495d-93d4-c5a00ae7917e
