name: mikelowe.xyz
on:
  pull_request:
    branches: main
    paths:
      - .github/workflows/mikelowe.xyz.yml
      - mikelowe.xyz/**
  push:
    branches: main
    paths:
      - .github/workflows/mikelowe.xyz.yml
      - mikelowe.xyz/**
jobs:
  Build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: mikelowe.xyz
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 0.72.0
      - run: hugo --minify
      - uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: mikelowe.xyz/public
          production-branch: main
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: fa67ed75-3514-4bdc-81bc-4cd3702919ad
