name: Portfolio
on:
  pull_request:
    branches: main
    paths:
      - .github/workflows/portfolio.yml
      - projects/portfolio/**
  push:
    branches: main
    paths:
      - .github/workflows/portfolio.yml
      - projects/portfolio/**
jobs:
  Build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: projects/portfolio
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 10
      - run: npm ci
      - run: npm test
      - run: npm run build
      - uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: projects/portfolio/build
          production-branch: main
          enable-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: 8f9edb0a-439c-4953-b079-c3df81002cbe
