name: Resume Template
on:
  pull_request:
    branches: main
    paths:
      - .github/workflows/resume-template.yml
      - projects/resume-template/**
  push:
    branches: main
    paths:
      - .github/workflows/resume-template.yml
      - projects/resume-template/**
jobs:
  Build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: projects/resume-template
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 10
      - run: npm ci
      - run: npm test
      - run: npm run build
      - uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: projects/resume-template/build
          production-branch: main
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: d322906a-b6c9-4235-9caf-8eb94370c563
