name: Simon Game
on:
  pull_request:
    branches: main
    paths:
      - .github/workflows/simon-game.yml
      - projects/simon-game/**
  push:
    branches: main
    paths:
      - .github/workflows/simon-game.yml
      - projects/simon-game/**
jobs:
  Build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: projects/simon-game
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 10
      - run: npm ci
      - run: npm test
      - run: npm run build
      - uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: projects/simon-game/build
          production-branch: main
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: 8bfe50db-0033-4849-8c70-39864713e466
