name: Snake
on:
  pull_request:
    branches: main
    paths:
      - .github/workflows/snake.yml
      - projects/snake/**
  push:
    branches: main
    paths:
      - .github/workflows/snake.yml
      - projects/snake/**
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: temurin
      - uses: gradle/gradle-build-action@v2
      - working-directory: projects/snake
        run: |
          ./gradlew desktop:assemble
          ./gradlew desktop:check
