name: Strimko
on:
  pull_request:
    branches: main
    paths:
      - .github/workflows/strimko.yml
      - projects/strimko/**
  push:
    branches: main
    paths:
      - .github/workflows/strimko.yml
      - projects/strimko/**
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: corretto
      - uses: gradle/gradle-build-action@v2
      - working-directory: projects/strimko
        run: |
          ./gradlew check jacocoTestReport
      - uses: codecov/codecov-action@v2
        with:
          flags: Strimko
          fail_ci_if_error: true
