name: Tic-Tac-Toe
on:
  pull_request:
    branches: main
    paths:
      - .github/workflows/tic-tac-toe.yml
      - projects/tic-tac-toe/**
  push:
    branches: main
    paths:
      - .github/workflows/tic-tac-toe.yml
      - projects/tic-tac-toe/**
jobs:
  Build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: projects/tic-tac-toe
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 10
      - run: npm ci
      - run: npm test
      - run: npm run build
      - uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: projects/tic-tac-toe/build
          production-branch: main
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: 359eee0b-bc50-4268-b538-913a8c120b5a
