name: Trainspotting Choose Quote Machine
on:
  pull_request:
    branches: main
    paths:
      - .github/workflows/trainspotting-choose-quote-machine.yml
      - projects/trainspotting-choose-quote-machine/**
  push:
    branches: main
    paths:
      - .github/workflows/trainspotting-choose-quote-machine.yml
      - projects/trainspotting-choose-quote-machine/**
jobs:
  Build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: projects/trainspotting-choose-quote-machine
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 10
      - run: npm ci
      - run: npm test
      - run: npm run build
      - uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: projects/trainspotting-choose-quote-machine/build
          production-branch: main
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: d66bb43e-8d3d-4cd6-9cf3-8cd9c205e4cf
