name: Tribute Page
on:
  pull_request:
    branches: main
    paths:
      - .github/workflows/tribute-page.yml
      - projects/tribute-page/**
  push:
    branches: main
    paths:
      - .github/workflows/tribute-page.yml
      - projects/tribute-page/**
jobs:
  Build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: projects/tribute-page
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 10
      - run: npm ci
      - run: npm test
      - run: npm run build
      - uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: projects/tribute-page/build
          production-branch: main
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: d2213d56-4d8f-4bdc-839f-e1dd61f35f3c
